"""While_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KqAtFQc4MNsCEjewr4Q5KKJn-IQleAWy

1. while loop repeatedly executes a block of code as long as a condition is True.

Syntax:
while condition:
    # code block

2. Condition is checked before each iteration (pre-test loop).

3. Loop stops automatically when the condition becomes False.

4. Can run infinite loops if condition never becomes False.

5. break statement exits the loop immediately.

6. continue statement skips the current iteration and goes to the next.

7. else block (optional) executes if the loop ends naturally (without break).

8. Can use counter variables to control the number of iterations.

9. Commonly used when number of iterations is unknown in advance.

10. Can loop through lists, strings, or any iterable using index or length.

11. Nested while loops are allowed for multi-level iteration.

12. Can combine with input() for user-driven loops.

13. Infinite loops are usually written as:
while True:
    # code

14. Avoid modifying the condition incorrectly to prevent infinite loops or skipped iterations.


https://chatgpt.com/s/t_693c669fddf881919b6c75e01646a413

You are an expert Python instructor and algorithmic thinker.

Teach me the Python `while` loop from absolute beginner level to advanced level.
Assume I am a beginner who wants to build strong logic and write programs independently.

Follow these strict rules:
1. Explain everything step by step.
2. Use simple English + easy logic explanations.
3. Use real-life analogies where possible.
4. Show dry runs for every important example.
5. Explain WHY each line of code is written.
6. Gradually increase difficulty (very basic → intermediate → advanced).
7. Include common mistakes and how to fix them.
8. Include practice questions after each section.
9. Do NOT skip any concept.
10. Keep examples short but meaningful.

Cover ALL of the following topics in order:

-----------------------------
SECTION 1: Basics
-----------------------------
- What is a while loop?
- Why we use while loop?
- Difference between while loop and for loop
- Syntax of while loop
- Loop condition (True / False)
- Counter variable concept
- Infinite loop (what it is and how it happens)
- How to stop a loop correctly

-----------------------------
SECTION 2: Control Flow
-----------------------------
- Incrementing and decrementing counters
- Using while loop with numbers
- Printing patterns using while loop
- Using multiple conditions
- Logical operators (and, or, not) in while loop
- Nested while loops (complete explanation)

-----------------------------
SECTION 3: Keywords
-----------------------------
- break (with dry run)
- continue (with dry run)
- pass
- else with while loop

-----------------------------
SECTION 4: Working with Data
-----------------------------
- Using while loop with lists
- Accessing list using index
- Searching elements in list
- Counting occurrences
- Removing elements safely
- While loop vs list comprehension (comparison)

-----------------------------
SECTION 5: Input & Validation
-----------------------------
- Taking user input using while loop
- Input validation
- Menu driven programs
- Password / PIN checking system
- Repeating program until user exits

-----------------------------
SECTION 6: Logic Building
-----------------------------
- Reverse a number using while loop
- Check palindrome
- Count digits
- Sum of digits
- Factorial using while loop
- Fibonacci series using while loop

-----------------------------
SECTION 7: Patterns (VERY IMPORTANT)
-----------------------------
- Number patterns
- Star patterns
- Alphabet patterns
- Pyramid patterns
- Nested while loop patterns with dry run

-----------------------------
SECTION 8: Advanced Concepts
-----------------------------
- While loop with flags
- While True pattern
- Loop optimization
- Time complexity understanding
- Common interview questions
- Real-world use cases

-----------------------------
SECTION 9: Debugging & Mistakes
-----------------------------
- Most common beginner mistakes
- Infinite loop debugging
- Off-by-one errors
- Wrong condition issues

-----------------------------
SECTION 10: Practice & Challenge
-----------------------------
- Beginner exercises
- Intermediate exercises
- Advanced challenges
- Mini projects using while loop
- Interview-style questions with solutions

At the end:
- Provide a summary
- Provide a learning checklist
- Provide next steps to master loops fully

Start teaching now.

How to use this prompt effectively

Paste it into ChatGPT, Gemini, Claude, DeepSeek, etc

Ask the model to teach section by section

Practice every example by typing code yourself

Ask for extra dry runs if needed

https://chatgpt.com/share/69490682-8088-8012-b46a-11171453de97
"""

i = 1              # starting point (counter variable)
while i <= 10:      # condition → loop runs while this is True
    print(i)       # work we want to repeat
    i = i + 1      # change the value → VERY IMPORTANT

# count = 1 → starting point
# count <= 10 → stopping condition
# count += 1 → moves loop forward

# even numbers from 2 to 10
nums=2
while nums<=10:
  print(nums)
  nums=nums+2

count=1 #iterator
while count<=5:
  print("Hello")
  count=count+1
print(count)

# Decrements
count=10
while count>=1:
  print(count)
  count-=1

# even numbers from 2 to 10
nums=2
while nums<=10:
  print(nums)
  nums=nums+2

#using multiple condition
i = 1
while i>=1 and i<=10:
  print(i)
  i=i+1
# Loop runs only when BOTH conditions are True

# logical operators
i = 1
while not i < 5:
    print(i)
    i += 1

# printing odd number from 1 to 9
count = 1        # start from first odd number
while count <= 9:  # stop at 9
    print(count)   # show current odd number
    count = count + 2  # jump to next odd number

# You have a grocery bag. You want to remove items one by one until the bag becomes empty.
grocery=["egg","bread","milk","Juice"]
while len(grocery)>0:
  item=grocery.pop()
  print("Removed=", item)
  print("Remaining items=",grocery)

# Break controlling loop

# Purpose: Ends the loop even if condition is still True
# nothing will run after break
i=1
while i<=5:
  if i==3:
    break
  print(i)
  i=i+1

# continue
# Skip current iteration
# Purpose:Skip remaining code in current iteration Go to next iteration of loop
# Example:

# i = 0
# while i < 5:
#     print(i)
#     i=i+1
#     if i == 3:
#         continue
# Aapne continue use kiya, magar is case me iska koi effect nahi
# continue tab useful hota hai jab uske baad koi aur code ho jo skip karna ho
i = 0
while i < 5:
    i += 1
    if i == 3:
        continue
    print(i)

# Else with while loop
# Purpose:
# Executes after loop finishes naturally (condition becomes False)
# Does not run if loop is stopped by break
i = 1
while i <= 3:
    print(i)
    i += 1
else:
    print("Loop finished normally")

# Else will not run after break
i = 1
while i <= 3:
    if i == 2:
        break
    print(i)
    i += 1
else:
    print("Loop finished normally")

# # Write a while loop that prints numbers 1 to 5, but skips 3 using continue.
i=0
while i<=5:
  i=i+1
  if i==3:
    continue
  print(i)
# Q2: Write a while loop that prints numbers 1 to 5, but stops if number is 4 using break, and use else to print "Loop completed".
i = 1
while i <= 5:
    if i == 4:       # agar number 4 ho jaye
        break        # loop yahan stop ho jaye
    print(i)         # print current number
    i += 1           # counter increment

else:                # else tab execute hota hai agar loop **normal terminate** ho
    print("Loop completed")



# continue → skip current iteration
# break → stop whole loop
# else → runs only if loop ends naturally

# when we want that our loop should stop after meeting specific condition
grocery1=["egg","bread","milk","Juice"]
while len(grocery1)>0:
  item1=grocery1.pop()
  print("Removed",item1)
  if item1=="milk":
    break
    print("Found milk-stop looping.")

x = 0
while x > 0:           # Condition is false initially
    print("Inside loop")
    x -= 1
print("Loop has ended")

i = 1
while i <= 3:
    j = 1
    while j <= 2:
        print(i,j)
        j += 1
    i += 1

# print this as pattern
# 1 1
# 2 2
# 3 3
# i = 1
# while i <= 3:
#         print(i, i)
#         i = i + 1

i = 1
while i <= 3:
    j = 1
    while j <= 2:
        print(i, end=" ")
        j = j + 1
    print()
    i = i + 1

# j is reset inside the outer loop → inner loop runs fully each time
# print(i, end=" ") → prints on the same line
# print() → moves to next line after inner loop finishes
# i increments → moves to next outer loop

# i ko 1 se start karte hain, yeh **outer loop ka counter** hai (lines ke liye)
i = 1
# outer while loop: jab tak i 5 se chhota ya equal hai, loop chalega
while i <= 5:
    # j ko 1 se start karte hain, yeh **inner loop ka counter** hai (har line me stars ke liye)
    j = 1
    # inner while loop: jab tak j i se chhota ya equal hai, "*" print hota rahega
    while j <= i:
        # "*" print karo ek line me, aur end="" se **newline nahi hota**
        print("*", end="")
        # inner loop counter ko increment karo, warna infinite loop ban jayega
        j = j + 1
    # inner loop complete → newline print karo, taki agla row nayi line me aaye
    print()
    # outer loop counter ko increment karo, next line ke liye
    i = i + 1

# Assignment_#_2
# print the pattern
# 1
# 12
# 123
# 1234
# 12345

i=1
while i<=5: #outer loop explain number of rows
  j=1
  while j<=i: #inner loop explain how many values each row contain
    print(j, end="")
    j=j+1
  print()
  i=i+1

# print the pattern
# 1
# 22
# 333
# 4444
# 55555
# Algorithim
# Step 1: Row 1 se start karo
# Step 2: Har row me
#   • row number print karo
#   • utni baar jitna row number hai
# Step 3: Ek row complete ho jaye to next line
# Step 4: Next row par jao
# # Step 5: Row 5 tak repeat karo

i=1
while i<=5:
  j=1
  while j<=i:
    print(i, end="")
    j=j+1
  print()
  i=i+1

# print the pattern here
# 1
# 23
# 456
# 78910
num=1
i=1
while i<=4: #outer loop explain number of rows
  j=1
  while j<=i: #inner loop explain how many values each row contain
    print(num, end="")
    num=num+1
    j=j+1
  print()
  i=i+1

# print the pattern
# 5
# 44
# 333
# 2222
# 11111

i = 5
while i >=1:          # rows: 5 se 1 tak
    j = 1
    while j <= 6 - i:  # har row mein numbers ka count
        print(i, end="")
        j = j + 1
    print()
    i = i - 1

# print the pattern
   #
  ##
 ###
####
i = 1
while i <= 4: #loop defining number of rows
    b = 1
    while b <= 4 - i: # this is a loop for blank spaces in each row
        print(" ", end="")
        b = b + 1
    j = 1
    while j <= i: # loop for number of times in each row
        print("#", end="")
        j = j + 1
    print()
    i = i + 1

# print the pattern
#####
####
###
##
#
i = 5
while i >= 1:          # total rows
    j = 1
    while j <= i:      # har row mein # ki count
        print("#", end="")
        j = j + 1
    print()            # new line
    i = i - 1

# print the pattern
#
##
###
####
#####
i = 1
while i <= 5:          # total rows
    j = 1
    while j <= i:      # har row mein # ki count
        print("#", end="")
        j = j + 1
    print()            # new line
    i = i + 1

# print the pattern
# A
# BB
# CCC
# DDDD
# EEEEE
i = 1
while i <= 5:           # total rows
    j = 1
    while j <= i:       # har row mein letters ka count
        print(chr(64 + i), end="")  # 65 = 'A'
        j = j + 1
    print()
    i = i + 1

# SECTION 4: WORKING WITH DATA
# using while loop with list
# You can iterate through a list using a counter variable (index).

numbers = [10, 20, 30, 40, 50]
i=0
# while i<=len(numbers)-1:
while i<len(numbers):
  print(numbers[i])
  i=i+1

# Finding a Value in list

numbers = [10, 20, 30, 40]
i = 0
while i < len(numbers):
    # print(i)
    if numbers[i] == 30:
        print("Found 30 at index", i)
        # break
    i += 1

# Q6) Do lists diye gaye hain. Har element ko multiply karke naye list mein store karein.
list1 = [2, 4, 6, 8]
list2 = [3, 5, 7, 9]

result = []

i = 0

while i < len(list1):
    result.append(list1[i] * list2[i])
    i = i + 1
print(result)

#Q_7 Ek list diya gaya hai. Sirf even numbers ko alag list mein store karein using while loop.
numbers = [5, 12, 7, 8, 20, 3, 14, 9]

even_numbers = []
i = 0

while i < len(numbers):
    if numbers[i] % 2 == 0:
        even_numbers.append(numbers[i])
    i = i + 1

print(even_numbers)

# Q8) Ek list diya gaya hai. Har element ko uske index number se multiply karke naye list mein store karein.
numbers = [5, 10, 8, 20]

result = []
i = 0

while i < len(numbers):
    result.append(numbers[i] * i)
    print(numbers[i],"*", i, "=", result[i])
    i = i + 1

# Q10) Ek list hai. Har element ko usse pehle wale saare elements ke sum se compare karein aur agar bara hai to "Yes" nahi to "No" print karein.
# for example:

numbers = [5, 10, 8, 20, 15, 50]
i = 0
while i < len(numbers):
    if i == 0:
        print("No")   # pehle element ka comparison nahi
    else:
        prev_sum = 0
        j = 0
        while j < i:
            prev_sum = prev_sum + numbers[j]
            j = j + 1

        if numbers[i] > prev_sum:
            print("Yes")
        else:
            print("No")
    i = i + 1

i=1
while i<5:
  j=1
  while j<5:
    print("value of j =",j)
    j=j+1
  i=i+1

nums = [1, 2, 3, 4, 5, 6, 7, 8]

result = []
i = 0

while i < len(nums):
    if nums[i] % 2 != 0:   # odd number
        result.append(nums[i])
    i = i + 1

print(result)

# printing Even and Odd numbers from a given list
numbers = [11, 14, 17, 20, 23, 26]
i=0
while i<len(numbers):
  if numbers[i]%2==0:
    print("Number at index", i, "is Even", numbers[i])
  else:
    print("Number at index", i, "is Odd", numbers[i])
  i+=1

# Using a while loop, count how many numbers are greater than 15 in the same list.
nums10 = [11, 14, 17, 20, 23, 26]
i=0
while i<len(nums10):
  if nums10[i]>15:
    print(nums10[i],"at index", i, "is Greater than ", 15)
  i+=1

# Using a while loop, count how many numbers are greater than 15 in the same list and remove that number
nums10 = [11, 14, 17, 20, 23, 26]
i = 0

while i < len(nums10):
    if nums10[i] > 15:
        print(nums10[i], "removed")
        nums10.pop(i)
    else:
        i += 1

nums10 = [11, 14, 17, 20, 23, 26]
i = 0

# remove numbers greater than 15
while i < len(nums10):
    if nums10[i] > 15:
        nums10.pop(i)
    else:
        i += 1

# print remaining numbers
print("Remaining numbers in list:")
for num in nums10:
    print(num, end=",")

# SECTION 5: INPUT & VALIDATION (Part 1)

# This section teaches you how real programs behave:
# They take input
# They repeat
# They validate mistakes
# They don’t crash

# Real-life analogy 🧠
# 1.ATM keeps asking PIN
# 2.Website keeps asking password
# 3.Game keeps asking “Play again?”


# You will be able to know:
# User input with while loop
# Validation
# Menu logic
# Exit-controlled loops

#1 Ask number until user enters 5

num=int(input("Enter a number: "))
while num!=5:
  print("Incorrect number,Try again")
  num=int(input("Again enter a number: "))
print("Correct number")

#2 Input Validation
# Problem:
# Users can enter wrong input.
# Example:
# Age should be positive.

age=int(input("Enter your age: "))

while age<=0:
  print("Invalid age")
  age=int(input("Enter your age: "))
print("Your age is valid:", age)


# Common Beginner Mistake
# while age < 18:
#     print("Too young")
# ❌ Infinite loop (age never changes)
# ✔️ Always update input inside loop

# Menu-Driven Program (CORE SKILL)

choice = 0

while choice != 3:
    print("1. Say Hello")
    print("2. Say Bye")
    print("3. Exit")

    choice = int(input("Enter choice: "))

    if choice == 1:
        print("Hello!")
    elif choice == 2:
        print("Bye!")
    elif choice == 3:
        print("Exiting...")
    else:
        print("Invalid choice")

# Loop keeps program alive
# Exit controlled by user
# This is real-world logic

# Repeating program until user exits
# Pattern to REMEMBER 🧠

# while True: #full control deta hai user ko
#     # program code
#     if exit_condition:
#         break #exit ka manual switch

# # This is very powerful and used everywhere.

while True:
    print("1. Check Balance")
    print("2. Withdraw")
    print("3. Exit")

    choice = input("Choose option: ")

    if choice == "1":
        print("Your balance is 50000")

    elif choice == "2":
        print("Amount withdrawn")

    elif choice == "3":
        print("Thank you!")
        break   # 🚪 EXIT ATM

    else:
        print("Invalid option")

# Write a program that:  Keeps asking the user to enter a number ,stops only when user enters 0

n1=int(input("Enter a number: ")) #Input taken before loop


while n1 !=0: #Loop stops only when 0 is entered
  print("Please enter 0 to exit")
  n1=int(input("Enter a number: ")) #Input updated inside loop
print("Number is valid")
print("Programme Ended")

# Section 6: LOGIC BUILDING
# This section turns you from syntax learner → problem solver.

# Rule yaad rakho
# n < 10 → n % 10 = n
# n ≥ 10 → last digit milta hai

n = 123

while n > 0:
    digit = n % 10  #Give last digit
    print(digit)
    n = n // 10 #remove last digit

# Rversing a number
# Step 1: Take input from user
n = int(input("Enter a number to reverse: "))

# Step 2: Initialize reverse number
reverse = 0

# Step 3: Loop until number becomes 0
while n != 0:
    last_digit = n % 10                  # get last digit
    reverse = reverse * 10 + last_digit  # add it to reversed number
    n = n // 10                          # remove last digit from original number

# Step 4: Print the reversed number
print("Reversed number is:", reverse)

# Dry Run:
# last_digit = n % 10        # 123 % 10 = 3
# reverse = reverse * 10 + last_digit  # 0*10 + 3 = 3
# n = n // 10                # 123 // 10 = 12
# n = 12
# last_digit = 3
# reverse = 3


# last_digit = n % 10        # 12 % 10 = 2
# reverse = reverse * 10 + last_digit  # 3*10 + 2 = 32
# n = n // 10                # 12 // 10 = 1
# n = 1
# last_digit = 2
# reverse = 32

# Check Palindrome: A number is a palindrome if it reads the same forwards and backwards.e.g 121,454,676

# Step 1: Input number
n = int(input("Enter a number: "))

# Step 2: Store original number
original = n

# Step 3: Initialize reverse
reverse = 0

# Step 4: Reverse the number
while n != 0:
    last_digit = n % 10
    reverse = reverse * 10 + last_digit
    n = n // 10

# Step 5: Check palindrome
if reverse == original:
    print("The number is a palindrome")
else:
    print("The number is NOT a palindrome")

# counting digits in a givrn value
n = int(input("Enter a number: "))
count = 0
temp = n  # store original number if needed later

while n != 0:
    n = n // 10
    count += 1

print("Number of digits in", temp, "is:", count)

# Counting and sum of digits

n = int(input("Enter a number: "))
count = 0
sum_digits = 0
Exact = n  # store original number

while n != 0:
    last_digit = n % 10      # get last digit
    sum_digits = sum_digits + last_digit # add to sum
    n = n // 10              # remove last digit
    count += 1               # increment count

print("Number of digits in", Exact, "is", count)
print("Sum of digits in", Exact, "is", sum_digits)

# Write a program that asks user for a number and prints factorial
# If user enters 0, print 1 (0! = 1)

n=int(input("Enter a number: "))
factorial=1
while n > 0:
  factorial=factorial*n
  n=n-1
print(factorial)

n = int(input("Enter number of terms: "))

first = 0
second = 1
count = 1

while count <= n:
    print(first, end=" ")
    next = first + second
    first = second
    second = next
    count = count + 1

# Sectioin 8
# flag variables
while True:
    choice = input("Enter 'q' to quit: ")

    if choice == 'q':
        break

    print("You are still inside the loop")

# while True + break: That’s exactly what professionals use for menus, games, servers, and real apps.

# Loop Optimization
# Bad Loop
# i = 1
# while i <= 20:
#     if i == 5:
#         print("Found")
#     i += 1

# Good Loop Exit the loop as soon as your goal is achieved
i = 1
while i <= 100:
    if i == 5:
        print("Found")
        break #this break here optimize loop
    i += 1


#  Real-World Use Cases

#  Menu-driven programs
#  ATM systems
#  Server request handling
#  Login systems
#  Games (main loop)
#  Input validation

# SECTION 9: Debugging & Common Mistakes (While Loop)

# Mistake 1: Counter not changing (INFINITE LOOP)
# Every while loop must move toward its stopping condition
i = 1
while i <= 5:
    print(i)
    break

n = 10
while n != 0:
    print(n)
    n = n + 1

# n starts at 10
# Condition: n != 0
# n keeps increasing → never becomes 0


# 9.3 — Off-by-One Errors

i = 1
while i < 5:
    print(i)
    i += 1 #no number 5

# < → excludes last value
# <= → includes last value

# 9.5 — Misusing continue
# iterator will be Before coninue

i = 0
while i < 5:
    i += 1
    if i == 3:
        continue
    print(i)

# Key Debug Rule (REMEMBER THIS)
# If a while loop misbehaves, check the counter first.

"""SECTION 10: Practice & Challenges — While Loops
Level 1: Beginner

Print numbers 1 to 10.

Print even numbers from 2 to 20.

Take positive numbers from user until 0 is entered and print their sum.

Reverse a number using a while loop.

Count digits of a number.

Sum of digits of a number.

Check if a number is a palindrome.

Take a password input until correct password is entered.

Print multiplication table of a given number.

Take numbers until negative number is entered; count how many numbers were entered.

Level 2: Intermediate

Print Fibonacci series up to n terms.

Find factorial of a number.

Print all prime numbers up to n.

Count even and odd numbers from user input (stop on 0).

Print pattern:

*
**
***
****


Print reverse of a string without using built-in reverse.

Remove all occurrences of a specific number from a list using while loop.

Menu-driven program: Add, Subtract, Multiply, Divide until user chooses Exit.

Check Armstrong number.

Sum of all digits in even positions of a number.

Level 3: Advanced

Print number patterns using nested while loops:

1
22
333
4444


Pyramid star pattern:

   *
  ***
 *****
*******


Input validation system with multiple conditions (e.g., password must contain number, letter, symbol).

While loop with flags for menu-driven banking system.

Detect infinite loops and fix them in a given snippet.

Generate first n prime numbers.

Create a simple guessing game until user guesses correctly.

Count digits, sum of digits, product of digits in a single loop.

Multiplication of all elements in a list using while loop.

Fibonacci series until a number exceeds m (dynamic end, not fixed n).

Level 4: Mini Projects / Challenges

ATM Simulator using while loop, menu, PIN verification, balance check, deposit & withdrawal.

Number Puzzle Game: Guess a number until correct; give hints high/low.

Student Attendance Tracker: Enter student names and mark present/absent; loop until all students entered.

Simple Banking System: Keep transaction log, show statement, repeat until exit.

Palindrome Finder: Take multiple numbers from user, find and print all palindromes.

Pattern Printer: Ask user type of pattern (number, star, pyramid) and size; print pattern.

Password Strength Checker: Keep asking until strong password entered.

List Cleaner: Remove all even numbers from a list using while loop.

Sum & Factorial Game: Take numbers from user, calculate sum, factorial, and check if result is palindrome.

Fibonacci Challenge: Print Fibonacci series and count how many are even numbers.

"""