# -*- coding: utf-8 -*-
"""List_data_type.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPJfup7Ezlq2AbmWjfR33Mo8hM74GfYX
"""

def make_list(text):
    parts = text.split()      # space par tod diya
    result = []

    for value in parts:
        result.append(int(value))  # har value ko number banaya

    return result

data = "10 20 30 40 50"
numbers = make_list(data)
print(numbers)

num=[10,20,30,40,50]

# Add number in list at end
num.append(60)
print(num)

# Recursive list woh list hoti hai jo khud ko hi apne andar reference karti hai.
a=[1,2]
a.append(a)
print(a)
print(len(a))

# add number in list at any index
num.insert(1,5)
print(num)

# extend() is used to add multiple values at once(usually another list)
num1 = [10, 20, 30]
num2 = [40, 50, 60]

num1.extend(num2)
print(num1)

# ✔ pop() → removes one item
# ✔ remove() → removes one specific value
# ✔ clear() → removes everything
list1=[10,20,30,40,50]
# remove value from list at specific index(default last)
list1.pop(0)
print(list1)
# remove by matching value or name
#Ex_1
list1.remove(20)
print(list1)
#Ex_2
fruits = ["apple", "banana", "grapes", "banana"]
fruits.remove("banana")
print(fruits)

# Clear functioin remove all items from list and make empty list
num3 = [10, 20, 30]
num3.clear()
print(num3)

result=list("1020456789")
print(result)

digits = list(map(int, "1020456789"))
print(digits)

# indexing
# Modify values, Change/replace value by index:

list2=["apple", "Bananna", "mangoes"]
print(list2)
list2[1] = "Oranges"
print("Replaced by oranges = ", list2)
list2[0]
list2[0:2] #last index is exclusive
#Ex_2
num5 = [1, 2, 3, 4, 5]
num5[1:4] = [9, 8, 7]   # replaces 2,3,4
print(num5)

# .in
# in checks if a value exists in a list, Returns True if it exists, False if not

list3=["apple", "banana", "cherry"]
print("apple" in list3)
print("mango" in list3)

num6= [10,20,30,40,50]
print(20 in num6)

text = "Programming"
print("gram" in text)

# to find the indec of vale in list first occurence of value in list only
num7=[10,20,30,40,30,50,30]
print(num7.index(30))
print(num7.count(30))

# Using sort() to arrange a list
# sort() arranges list items in ascending order by default

list3=[30,10,50,80,90,45] #Asscending order
list3.sort()
print("Asscending order =", list3)

# for descending
list3.sort(reverse=True) #Descending order
print("Descending order =", list3)

# for reverse in list3
# Changes original list
# Returns None
list4 = [5, 3, 8, 1]
list4.reverse()
print("Reverse of value =", list4)


# A method returns an iterator in reverse order?
nums = [1, 2, 3, 4]
rev = reversed(nums)
print(list(rev))

# slicing a list
# list5[start : End(exclusive)]
# list[start : end : step]
# default step is +1 move from left  to right.
#   if step = -1
#   start or end is blank , Python automatically full reverse the list item or str characters.


list5=[10,20,30,40,50,60,70,80,90]

str= "saqib"

print("1.",list5[0:7])
print("2.",list5[2:4])
print("3.",list5[:4])
print("4.",list5[4:])
print("5.",list5[5:])

# Negative Slicing with steps
print("6.",list5[-4:-1])
print("7.",list5[-1:-4:-1])
print("8.",list5[-1])
print("9.",list5[:-1])
print("10.",list5[-7:-2])

# slicing in string because python treat string as list of characters
print("11.",str[:-1])
print("12.",str[::-1])
print("13.",str[-3:-1])
print("14.",str[-1::-1])
print("15.",str[:])

# Slicing with steps
print("16.",list5[0:8:2])
print("17.",list5[0::2])

print("18.",[1,2,3][::-1][0])

DNA_Sequence="ATCGGCTA"
reverse_seq = DNA_Sequence[::-1]
print(reverse_seq)

if reverse_seq == DNA_Sequence:
    print(reverse_seq, "is", "Palindrome")
else:
    print("Not Palindrome")

list_6=[7,5,78,90,34,45,100]
max_value=max(list_6)
print("Maximum value is =", max_value)

min_value=min(list_6)
print("Mininmum value is =", min_value)

# list comprehension and copy
# Yahan nayi list nahi banti a aur b same list ko point karte hain
# Change ek jagah karo, dono mein dikhegi

a=["Apple", "Oranges", "Bananna"]
b=a #just creting a reference
b.append("Mangoes")
print(a)
print(b)

# but here we get a new list
x=[1,2,3]
y=x.copy()
y.append(4)
print(x)
print(y)

# slicing can also give new copy

# comprehension = loop + condition + append sab ek line mein
# Jab bhi list comprehension likho, apne aap se 3 sawal poocho:

# 1️⃣ Mujhe kya chahiye?
# 2️⃣ Kahan se milega?
# 3️⃣ Koi condition hai?

# Phir likho:

# [what_you_want for item in source if condition]

# Socho: “Mujhe kis cheez ki list chahiye?”
# Example:
# Mujhe squares chahiye
# Mujhe even numbers chahiye
# Mujhe sirf strings chahiye
# Phir formula lagao:

# [what_to_add for item in source if condition]

# [new_value for item in list_or_range]
# Socho is tarah:

# “Mujhe ek new list chahiye
# jisme har item ka new_value ho”

x = [56, 47, 89, 90, 77, 11, 20, 22]
result = [num for num in x if num % 2 == 0]
print(result)

# Separating a string data from mixed list
data = [10, "apple", 3.5, "banana", True, "cat"]
strings = [x for x in data if isinstance(x, str)]

x = 10
print(isinstance(x, int))   # True
print(isinstance(x, str))   # False

y = "Hello"
print(isinstance(y, str))   # True
print(isinstance(y, int))   # False

z = 3.5
print(isinstance(z, float)) # True

nums = [10, 20, 30, 40, 50]
temp = nums[0]      # first element ko store karo
nums[0] = nums[-1]  # first element mein last daalo
nums[-1] = temp     # last element mein first value daalo

# Pythonic way
nums[0], nums[-1] = nums[-1], nums[0]
print(nums)


print(nums)

# 2D list
# A 2D list is a list of lists
# Think of it like a table: rows and columns

matrix=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
print("1.",matrix)

# indexing in 2d list
print("2.",matrix[0])
print("3.",matrix[1])
print("4.",matrix[2])
print("5.",matrix[0][1]) #first index for row and 2nd for value in  row
print("6.",matrix[2][0])

# appending 2d list
matrix1 = [
    [10, 20],
    [30, 40]
]
matrix1.append([50,60])
print(matrix1)
matrix1[1].append(50)
print(matrix1)



"""Beginner Level (1–15)

How do you create a list with numbers 1, 2, 3?

Which method adds an element at the end of a list?

How do you remove the first occurrence of a value?

How do you find the index of the first occurrence of a value?

What is the difference between append() and extend()?

How do you reverse a list in-place?

Which method removes and returns the last item from a list?

How do you create a shallow copy of a list?

Which method removes all items from a list?

What does slicing list[1:4] return?

How do you access the last element of a list?

What happens if you append a list to itself?

How do you sort a list in ascending order?

How do you get the length of a list?

How do you check if an element exists in a list?

Intermediate Level (16–35)

How do you insert an element at a specific index?

What is the result of list1 + list2?

How can you repeat a list n times?

How do you get every second element of a list?

Which method returns an iterator in reverse order?

How do you find the maximum element in a list?

How do you find the minimum element in a list?

How do you count occurrences of an element in a list?

How do you remove an element by index?

How can you copy a list using slicing?

How do you combine two lists element-wise using a loop?

How do you sort a list in descending order?

How do you reverse a list using slicing?

How do you remove all even numbers from a list?

How do you extract only strings from a mixed list?

How do you flatten a 2D list using list comprehension?

How do you swap the first and last elements of a list?

How do you multiply each element by its index?

How do you remove duplicates while keeping order?

How do you find the sum of all elements in a list?

Advanced Level (36–50)

How do you find the second largest element in a list?

How do you rotate a list by n positions?

How do you check if a list is a palindrome?

How do you generate a list of squares using list comprehension?

How do you remove all elements satisfying a condition in-place?

How do you find indexes of all occurrences of a value?

How do you sort a list by a custom key, e.g., string length?

How do you merge two sorted lists efficiently?

How do you find elements common to two lists?

How do you find unique elements across two lists?

How do you deep copy a nested list?

How do you get running totals of a list?

How do you sort a list of tuples by the second element?

How do you replace all occurrences of a value in a list?

How do you implement a stack using a list?

If you want, I can also provide a ready-to-copy Python script that will automatically generate a PDF with these 50 questions, without answers, so you can print or practice directly.

Do you want me to do that?

I can also make a formatted printable PDF-style version with answers and hints for easy practice.

Do you want me to do that next?
"""

a=b=[1,2]
a=a+[3]
print(b)

# + creates a new list
# += modifies the same list

a=[1,2]
a=a+[3]
print(a)